### ISSUE TITLE
Cannot install from tabby plugin list

### ISSUE THREAD

**Issue by UyCode** [composer404/tabby-search-in-browser#2]
this plugin cannot install from tabby plugin list by clicking "Get" button.
this error occurs when i trying to install this plugin:
![image](https://user-images.githubusercontent.com/24651136/145046254-f9bb24d5-1100-4f96-8f69-c6e129e1df75.png)
`core.js:6456 ERROR Error: Uncaught (in promise): Object: {"code":"ETARGET","name":"tabby-search-in-browser","type":"version","wanted":"0.0.1","versions":["0.0.0"],"distTags":{"latest":"0.0.0"},"defaultTag":"latest","message":"No matching version found for tabby-search-in-browser@0.0.1.","stack":"tabby-search-in-browser: No matching version found for tabby-search-in-browser@0.0.1.\n    at pickManifest (D:\\Program Files\\Tabby\\resources\\app.asar\\node_modules\\npm\\node_modules\\npm-pick-manifest\\index.js:122:13)\n    at D:\\Program Files\\Tabby\\resources\\app.asar\\node_modules\\npm\\node_modules\\pacote\\lib\\fetchers\\registry\\manifest.js:43:18\n    at tryCatcher (D:\\Program Files\\Tabby\\resources\\app.asar\\node_modules\\npm\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (D:\\Program Files\\Tabby\\resources\\app.asar\\node_modules\\npm\\node_modules\\bluebird\\js\\release\\promise.js:517:31)\n    at Promise._settlePromise (D:\\Program Files\\Tabby\\resources\\app.asar\\node_modules\\npm\\node_modules\\bluebird\\js\\release\\promise.js:574:18)\n    at Promise._settlePromise0 (D:\\Program Files\\Tabby\\resources\\app.asar\\node_modules\\npm\\node_modules\\bluebird\\js\\release\\promise.js:619:10)\n    at Promise._settlePromises (D:\\Program Files\\Tabby\\resources\\app.asar\\node_modules\\npm\\node_modules\\bluebird\\js\\release\\promise.js:699:18)\n    at _drainQueueStep (D:\\Program Files\\Tabby\\resources\\app.asar\\node_modules\\npm\\node_modules\\bluebird\\js\\release\\async.js:138:12)\n    at _drainQueue (D:\\Program Files\\Tabby\\resources\\app.asar\\node_modules\\npm\\node_modules\\bluebird\\js\\release\\async.js:131:9)\n    at Async._drainQueues (D:\\Program Files\\Tabby\\resources\\app.asar\\node_modules\\npm\\node_modules\\bluebird\\js\\release\\async.js:147:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (D:\\Program Files\\Tabby\\resources\\app.asar\\node_modules\\npm\\node_modules\\bluebird\\js\\release\\async.js:17:14)\n    at processImmediate (internal/timers.js:461:21)","level":"error"}
tabby-search-in-browser: No matching version found for tabby-search-in-browser@0.0.1.
    at pickManifest (D:\Program Files\Tabby\resources\app.asar\node_modules\npm\node_modules\npm-pick-manifest\index.js:122:13)
    at D:\Program Files\Tabby\resources\app.asar\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:43:18
    at tryCatcher (D:\Program Files\Tabby\resources\app.asar\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Program Files\Tabby\resources\app.asar\node_modules\npm\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (D:\Program Files\Tabby\resources\app.asar\node_modules\npm\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (D:\Program Files\Tabby\resources\app.asar\node_modules\npm\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (D:\Program Files\Tabby\resources\app.asar\node_modules\npm\node_modules\bluebird\js\release\promise.js:699:18)
    at _drainQueueStep (D:\Program Files\Tabby\resources\app.asar\node_modules\npm\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\Program Files\Tabby\resources\app.asar\node_modules\npm\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\Program Files\Tabby\resources\app.asar\node_modules\npm\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\Program Files\Tabby\resources\app.asar\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate (internal/timers.js:461:21)
    at resolvePromise (file:///D:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:117164:31)
    at file:///D:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:117071:17
    at rejected (D:\Program Files\Tabby\resources\builtin-plugins\tabby-plugin-manager\dist\index.js:7987:89)
    at ZoneDelegate.invoke (file:///D:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:116323:26)
    at Object.onInvoke (file:///D:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:78477:33)
    at ZoneDelegate.invoke (file:///D:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:116322:52)
    at Zone.run (file:///D:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:116085:43)
    at file:///D:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:117227:36
    at ZoneDelegate.invokeTask (file:///D:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:116357:31)
    at Object.onInvokeTask (file:///D:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:78464:33)
    at ZoneDelegate.invokeTask (file:///D:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:116356:60)
    at Zone.runTask (file:///D:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:116129:47)
    at drainMicroTaskQueue (file:///D:/Program%20Files/Tabby/resources/app.asar/dist/bundle.js:116533:35)`

**Comment by UyCode** [comment]
Seems like npm cannot find this plugin version 0.0.1
